[workspace]
members = [
  "zomes/did-profiles"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hdk = { git = "https://github.com/holochain/holochain", rev="24ceb63bdea374d1936b723e1966caf2e55ebfdc", package="hdk"}
